module.exports = {
  title: `Bristol Inglés Profesional`,
  description: `Nos comprometemos con la calidad y la innovación, manteniéndonos a la vanguardia en la enseñanza de inglés. Contamos con docentes profesionales con los más altos grados académicos y certificaciones internacionales en lengua inglesa.`,
  keywords: `inglés, ingles, veracruz, xalapa, coatepec, adolescentes, niños, estudiar, aprender, cambridgem, esol, certificaciones, internacional, intercambios, universidad, bristol, english, canada, londres, london, england, inglaterra`,
  shortName: `Bristol`,
  lang: `es-MX`,
  email: `hola@bristolingles.com.mx`,
  telXalapa: `2288405791`,
  tel2Xalapa: `2288159338`,
  telCoatepec: `2288160533`,
  facebook: `https://www.facebook.com/bristolinglesprofesional/`,
  instagram: `https://www.instagram.com/bristolingles/`,
  facebookhref1: `https://connect.facebook.net`,
  facebookhref2: `https://scontent.fmid4-1.fna.fbcdn.net`,
  commodityAesthetics: `http://www.juancarlosvazquez.com/`,
  lasso: `https://www.linkedin.com/in/luislasssomx/`,
}